### ISSUE TITLE
Use dark scrollbar when editor is in dark theme

### ISSUE THREAD

**Issue by Nightcaat** [mroyale/MarioRoyaleDeluxe#17]
Tiny thing that bothers me that I will fix soonish

**Comment by terminalarch** [comment]
imagine dark text boxes..... it would be so awesome...

**Comment by Nightcaat** [comment]
Not actually completed smh my head
![](https://user-images.githubusercontent.com/26909213/226432878-c7cd7176-e164-45c9-8f05-2bedf96ac8b9.png)
Will do this not too long from now

**Comment by terminalarch** [comment]
Added in 4.3
