### ISSUE TITLE
In-game gamepad button does nothing

### ISSUE THREAD

**Issue by Nightcaat** [mroyale/MarioRoyaleDeluxe#18]

**Comment by Nightcaat** [comment]
Legacy’s doesn’t do anything either… did this ever work? I tried looking for the button to see what’s going on but couldn’t find it.

**Comment by terminalarch** [comment]
it only tells you that it's connected, there's no button functionality, this is the only thing related to it: (drawing it in the ui)
```js
if(this.game.input.pad.connected()) {
      var st = util.sprite.getSprite(uitex, PAD);
      context.drawImage(uitex, st[0], st[1], Display.TEXRES, Display.TEXRES, W-224, 40, 36, 36);
}
```
