### ISSUE TITLE
Restrict password length

### ISSUE THREAD

**Issue by Nightcaat** [mroyale/MarioRoyaleDeluxe#19]
Really long passwords can pose a serious problem: an 8,160 character password, for example, might allow you to save it but not log in, giving a Connection Interrupted screen with no errors in the console. This just happened to me because I am very smart.

Password length should be restricted to 4,096 characters. That’s still overkill but shouldn’t cause any issues.

**Comment by terminalarch** [comment]
Latest commit addresses this
