### ISSUE TITLE
Eliminate the scrollbar in the editor

### ISSUE THREAD

**Issue by Nightcaat** [mroyale/MarioRoyaleDeluxe#27]
Sometimes I get the scrollbar even in fullscreen. I will put an end to this

**Comment by terminalarch** [comment]
He did not put an end to it, chat

**Comment by Nightcaat** [comment]
Forgot to close this, I did this in https://github.com/mroyale/MarioRoyaleDeluxe/commit/1624c7c0278056117a050501f6854db8b938c5f8
