### ISSUE TITLE
Add selected world indicator in the editor

### ISSUE THREAD

**Issue by Nightcaat** [mroyale/MarioRoyaleDeluxe#28]
This was in Legacy but I forgot to bring it over

**Comment by terminalarch** [comment]
how do you plan on doing this it's a dropdown menu

**Comment by Nightcaat** [comment]
This refers to the active zone indicator, in the same way that the active layer is highlighted. This is how it looks in the Legacy editor:
![](https://user-images.githubusercontent.com/26909213/227540806-2aeed159-9c6d-4b23-b47f-392c905d70cc.png)
Not difficult, just never got to it

**Comment by terminalarch** [comment]
Added in 4.3
