### ISSUE TITLE
SMB1 World 2-1 flagpole can be jumped over

### ISSUE THREAD

**Issue by Nightcaat** [mroyale/MarioRoyaleDeluxe#33]
https://user-images.githubusercontent.com/26909213/225974000-063549d1-9217-42aa-b34a-0a54a0345332.mp4

**Comment by terminalarch** [comment]
grahhhh i'll fix this someday

**Comment by Nightcaat** [comment]
Fixed in https://github.com/mroyale/MarioRoyaleDeluxe/commit/a88c8feb8e97666261e01bd15ea788dfd8884e06
